<?php require('template/header.phtml');
require($_SERVER['DOCUMENT_ROOT'] . '/classes/database.php')
?>

<h3>Database link and fetch test</h3>

<?php
$dbHandle = database::Instance();
$dbHandle->query("select * from review");

$alldata = $dbHandle->resultset();
$rowcount =sizeof($alldata);
for ($i =0; $i <$rowcount; $i++){
    $row = $alldata[$i];
    echo "<p> $row[1] $row[2] $row[3] $row[4]</p>";
}

?>
<?php require('template/footer.phtml') ?>
