<?php
require($_SERVER['DOCUMENT_ROOT'] . '/classes/database.php')
?>
<h3>Login Status</h3>
<?php
$email = $_GET['username'];
$pass =  $_GET['password'];

$dbHandle = database::Instance();
$dbHandle->query("SELECT * FROM user WHERE email LIKE \"$email\" AND password = \"$pass\"");
$alldata = $dbHandle->resultset();
$rowcount =sizeof($alldata);

for ($i = 0; $i <$rowcount; $i++){
    $row = $alldata[$i];
    if ($row[3] == 1)
        echo "You've Logged in as " . $row[2] . ", You are an Admin";
    elseif($row[3] == 0)
        echo "You've Logged in as " . $row[2];
}
?>
