<!--
    User PAGE
    if an admin were to log in then they will be taken to this page.

    Contents:
        - Will have a survey
 -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login V1.6</title>
    <link rel="stylesheet" href="../css/bootstrap.css">
    <link rel="stylesheet" href="../css/bootstrap-theme.css">
    <link rel="stylesheet" href="../css/my-style.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="../images/icons/favicon.ico"/>
    <link rel="stylesheet" type="text/css" href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="../vendor/animate/animate.css">
    <link rel="stylesheet" type="text/css" href="../vendor/css-hamburgers/hamburgers.min.css">
    <link rel="stylesheet" type="text/css" href="../vendor/select2/select2.min.css">
    <link rel="stylesheet" type="text/css" href="../css/util.css">
    <link rel="stylesheet" type="text/css" href="../css/main.css">
</head>
<body class="container-login100">
    <div class="wrap-login101">
        <form class="form-style" method="post" action="index.php">
            <span class="survey-title">
                    Survey
                </span>
            <div class="wrap-input100 validate-input">
                <label class="surveyText">Platform:</label>
                <div class="input100">
                    <select class="searchOp" name="platform" required>
                        <option class="searchItem" value="AMT">AMT</option>
                        <option class="searchItem" value="UpWork">UpWork</option>
                        <option class="searchItem" value="Fiverr">Fiverr</option>
                        <option class="searchItem" value="ClickWork">ClickWork</option>
                    </select>
                </div>
            </div>
            <div class="wrap-input100 validate-input">
                <label class="surveyText" >Time spent looking for work:</label>
                <label class="surveyText-sub">In Hours</label>
                <input class="input100" name="timelooking" type="number" maxlength="6" max="200" min="1" step="0.5" oninput="javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);" required>
            </div>
            <div class="wrap-input100 validate-input">
                <label class="surveyText">Time spent working on task:</label>
                <label class="surveyText-sub">In Hours</label>
                <input class="input100" name="timeworking" type="number" maxlength="6" max="200" min="1" step="0.5" oninput="javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);" required>
            </div>

            <div class="wrap-input100 validate-input">
                <label class="surveyText">Wage:</label>
                <label class="surveyText-sub">(Currency/hr)</label>
                <div class="currency">
                    <div class="inputCurrency">
                        <select class="searchOp" name="CurrencySign" required>
                            <option class="searchItem" value="GBP">£</option>
                            <option class="searchItem" value="USD">$</option>
                            <option class="searchItem" value="EUR">€</option>
                            <option class="searchItem" value="YEN">¥</option>
                        </select>
                    </div>
                    <input class="inputCurrency inputCurrency-text" name="wage" type="number" maxlength="6" max="200" min="0" step="0.1" oninput="javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);" required>
                </div>
            </div>

            <div class="wrap-input100 validate-input">
                <label class="surveyText">Gender</label>
                <div class="input100">
                    <select name="gender" class="searchOp">
                        <option class="searchItem" value="M">Male</option>
                        <option class="searchItem" value="F">Female</option>
                        <option class="searchItem" value="O">Prefer not to Say</option>
                    </select>
                </div>
            </div>

            <div class="wrap-input100 validate-input">
                <label class="surveyText">Age</label>
                <div class="input100">
                    <input class="searchOp" name="age" type="number" maxlength="2" max="99" min="0">
                </div>
            </div>

            <div class="wrap-input100 validate-input">
                <label class="surveyText">Country</label>
                <div class="input100">
                    <input class="searchOp" name="country" type="text" maxlength="20">
                </div>
            </div>

            <div class="wrap-input100 validate-input">
                <label class="surveyText">Rating</label>
                <div class="input100">
                    <select class="searchOp" name="rating">
                        <option class="searchItem" value="0">0 Star</option>
                        <option class="searchItem" value="1">1 Star</option>
                        <option class="searchItem" value="2">2 Star</option>
                        <option class="searchItem" value="3">3 Star</option>
                        <option class="searchItem" value="4">4 Star</option>
                        <option class="searchItem" value="5">5 Star</option>
                    </select>
                </div>
            </div>
            <input class="login101-form-btn" type="submit" value="submit" name="submit">
        </form>
    </div>
</body>