<!--
A simple login form design
 - [ ] Need to sanitise data
-->
<div class="container login">
    <div class="row col-sm-10">
        <div class="span12">
            <form class="form-horizontal" action='page1.php' method='post'> <!-- Once Submitted, will send values to page1.php -->
                <fieldset>
                    <div id="legend col-sm-12">
                        <legend>Login</legend>
                    </div>
                    <div class="control-group col-sm-10">
                        <!-- Username -->
                        <label class="control-label"  for="username">Username</label>
                        <div class="controls">
                            <input type="text" id="username" name="username" placeholder="" class="input-xlarge">
                        </div>
                    </div>
                    <div class="control-group col-sm-10">
                        <!-- Password-->
                        <label class="control-label" for="password">Password</label>
                        <div class="controls">
                            <input type="password" id="password" name="password" placeholder="" class="input-xlarge">
                        </div>
                    </div>
                    <div class="control-group">
                        <!-- Button -->
                        <div class="controls buttonLogin col-sm-10">
                            <input class="btn btn-success" type="submit" value="Login"/>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>
