<!--
A simple login form design
 - [ ] Need to sanitise data
-->
<!DOCTYPE html>
<html lang="en">

<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Login V1.6</title>-->
<!--    <link rel="stylesheet" href="css/bootstrap.css">-->
<!--    <link rel="stylesheet" href="css/bootstrap-theme.css">-->
<!--    <link rel="stylesheet" href="css/my-style.css">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1">-->
<!--    <link rel="icon" type="image/png" href="images/icons/favicon.ico"/>-->
<!--    <link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">-->
<!--    <link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">-->
<!--    <link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">-->
<!--    <link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">-->
<!--    <link rel="stylesheet" type="text/css" href="css/util.css">-->
<!--    <link rel="stylesheet" type="text/css" href="css/main.css">-->
<!--</head>-->

<body>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <div class="login100-pic js-tilt" data-tilt>
                <img src="images/img-01.png" alt="IMG">
            </div>

            <form class="login100-form validate-form" action='<?php echo htmlentities($_SERVER['PHP_SELF']); ?>' method='post'>
					<span class="login100-form-title">
						User Login
					</span>
                <!-- Username -->
                <div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
                    <input class="input100" type="email" name="username" placeholder="Email" required>
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
                </div>
                <!-- Password -->
                <div class="wrap-input100 validate-input" data-validate = "Password is required">
                    <input class="input100" type="password" name="password" placeholder="Password" required>
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
                </div>
                <!-- Button -->
                <div class="container-login100-form-btn">
                    <input type="submit" value="submit" class="login100-form-btn" />
                </div>
                <!-- Register -->
                <div class="text-center p-t-136">
                    <a class="txt2" href="register.php">
                        Create your Account
                        <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>