<!--
A simple login form design
 - [ ] Need to sanitise data
-->
<?php require_once('template/header.phtml') ?>
<body>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <div class="login100-pic js-tilt" data-tilt>
                <img src="/images/ILO-Logo.png" alt="International Labor
                Organisation's Logo">
            </div>

            <form class="login100-form validate-form" action='<?php echo htmlentities($_SERVER['PHP_SELF']); ?>' method='post'>
					<span class="login100-form-title">
						User Login
					</span>
                <!-- Username -->
                <div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
                    <input class="input100" type="email" name="username" placeholder="Email" required>
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
                </div>
                <!-- Password -->
                <div class="wrap-input100 validate-input" data-validate = "Password is required">
                    <input class="input100" type="password" name="password" placeholder="Password" required>
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
                </div>
                <!-- Button -->
                <div class="container-login100-form-btn">
                    <input type="submit" name="submit" value="submit" class="login100-form-btn" />
                </div>
                <!-- This bit is for lazy styles -->
                <div class="text-center p-t-136">
                    <a class="txt2" href="#">

                        <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>