<?php require('Views/template/headerUser.phtml') ?>

    <h3>Register as a new Admin</h3>

    <!-- Import the registration validation script -->
    <script src="../js/register.js" ></script>
    <form name="registration-form" onsubmit="return validateRegisterForm()" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <div class="container">
            <label><b>Email</b></label>
            <input type="email" placeholder="Enter Email" name="email" required>
            <br />
            <label><b>Password</b></label>
            <input type="password" placeholder="Enter Password" name="psw" required>
            <br />
            <label><b>Repeat Password</b></label>
            <input type="password" placeholder="Repeat Password" name="psw-repeat" required>

            <br />

            <div class="clearfix">
                <input type="submit" name='submit' class="signupbtn" value="submit">
            </div>
        </div>
    </form>

    </div>
</div>
<?php if (isset($view->insert)) : ?>
    <p><?php echo $view->insert; ?></p>
<?php endif; ?>

<?php require('template/footer.phtml') ?>