<?php require_once('template/header.phtml') ?>
    <script src="../js/register.js" ></script>

<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100">
            <div class="login100-pic js-tilt" data-tilt>
                <img src="/images/ILO-Logo.png" alt="The International Labor
                Organisation's Logo">
            </div>
            <form class="login100-form validate-form" name="registration-form" onsubmit="return validateRegisterForm()" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">

                <span class="login100-form-title">
                    Register as a new Admin
                </span>
                <!-- Email -->
                <div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
                    <input class="input100" type="email" name="email" placeholder="Enter Email" required>
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                    </span>
                </div>
                <!-- Password -->
                <div class="wrap-input100 validate-input" data-validate = "Password is required">
                    <input class="input100" type="password" name="psw" placeholder="Enter Password"  required>
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                    </span>
                </div>
                <!-- Repeat Password -->
                <div class="wrap-input100 validate-input" data-validate = "Password is required">
                    <input class="input100" type="password" name="psw-repeat" placeholder="Repeat Password"  required>
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
                        <i class="fa fa-lock" aria-hidden="true"></i>
                    </span>
                </div>
                <!-- Button -->
                <div class="clearfix container-login100-form-btn">
                    <input type="submit" name='submit' class="signupbtn login100-form-btn" value="submit">
                </div>
                <!-- Login -->
                <div class="text-center p-t-136">
                    <a class="txt2" href="login.php">
                        Log into your account
                        <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
<?php if (isset($view->insert)) : ?>
    <p><?php echo $view->insert; ?></p>
<?php endif; ?>

<?php require('template/footer.phtml') ?>