<?php require('template/header.phtml') ?>

<h3>Welcome to Our Survey Form</h3>

<body>
<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" >
    <label>Platform:</label>
    <select name="platform" required>
        <option value="AMT">AMT</option>
        <option value="UpWork">UpWork</option>
        <option value="Fiverr">Fiverr</option>
        <option value="ClickWork">ClickWork</option>
    </select>
    <br>
    <label>Time spent looking for work:</label>
    <input name="timelooking" type="number" max="100" min="0" required>
    <br>
    <label>Time spent working on task:</label>
    <input name="timeworking" type="number" max="100" min="0" required>
    <br>
    <label>Wage(£/hr):</label>
    <input name="wage" type="number" max="100" min="0" step="0.01" required>
    <br>
    <input type="submit" value="submit" name="submit">
</form>

<?php if (isset($view->insert)) : ?>
    <p><?php echo $view->insert; ?></p>
<?php endif; ?>

</body>

<?php require('template/footer.phtml') ?>
