<?php require('template/header.phtml') ?>


<body>
<div>
    <form  action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <span>Worker survey</span>
        <label>Platform:</label>

        <select name="platform" required>
            <option value="AMT">AMT</option>
            <option value="UpWork">UpWork</option>
            <option value="Fiverr">Fiverr</option>
            <option value="ClickWork">ClickWork</option>
        </select>
</div>
<br>
<label>Time spent looking for work:</label>
    <input name="timelooking" type="number" max="100" min="0" required>
<br>
<label>Time spent working on task:</label>
<input name="timeworking" type="number" max="100" min="0" required>
<br>
<label>Wage(£/hr):</label>
<input name="wage" type="number" max="100" min="0" step="0.01" required>
<br>
<input type="submit" value="submit" name="submit">

</form>

<?php if (isset($view->insert)) : ?>
    <p><?php echo $view->insert; ?></p>
<?php endif; ?>
</div>
</body>

<?php require('template/footer.phtml') ?>
