<!--
    User PAGE
    if an admin were to log in then they will be taken to this page.

    Contents:
        - Will have a survey
 -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login V1.6</title>
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/bootstrap-theme.css">
    <link rel="stylesheet" href="css/my-style.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
    <link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
    <link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
    <link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
    <link rel="stylesheet" type="text/css" href="css/util.css">
    <link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body class="container-login100">
    <div class="wrap-login101">
        <form class="form-style" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
            <span class="survey-title">
                    Survey
                </span>
            <div class="wrap-input100 validate-input">
                <label class="surveyText">Platform:</label>
                <div class="input100">
                    <select class="searchOp" name="platform" required>
                        <option class="searchItem" value="AMT">AMT</option>
                        <option class="searchItem" value="UpWork">UpWork</option>
                        <option class="searchItem" value="Fiverr">Fiverr</option>
                        <option class="searchItem" value="ClickWork">ClickWork</option>
                    </select>
                </div>
            </div>
            <div class="wrap-input100 validate-input">
                <label class="surveyText" >Time spent looking for work:</label>
                <label class="surveyText-sub">In Hours</label>
                <input class="input100" name="timelooking" type="number" max="100" min="0" step="1" required>
            </div>
            <div class="wrap-input100 validate-input">
                <label class="surveyText">Time spent working on task:</label>
                <label class="surveyText-sub">In Hours</label>
                <input class="input100" name="timeworking" type="number" max="100" min="0" step="1" required>
            </div>

            <div class="wrap-input100 validate-input">
                <label class="surveyText">Wage:</label>
                <label class="surveyText-sub">(Currency/hr)</label>
                <div class="currency">
                    <div class="inputCurrency">
                        <select class="searchOp" name="platform" required>
                            <option class="searchItem" value="Pound">£</option>
                            <option class="searchItem" value="Dollar">$</option>
                            <option class="searchItem" value="Euro">€</option>
                            <option class="searchItem" value="Yen">¥</option>
                        </select>
                    </div>
                    <input class="inputCurrency inputCurrency-text" name="wage" type="number" max="100" min="0" pattern="\d*" step="0.1"required>
                </div>
            </div>

            <input class="login101-form-btn" type="submit" value="submit" name="submit">
        </form>
    </div>
</body>