<!--
    User PAGE
    if an admin were to log in then they will be taken to this page.

    Contents:
        - Will have a survey
 -->
<body class="container-login100">
<div class="wrap-login101">
    <form class="form-style" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <div class="wrap-input100 validate-input">
            <span class="survey-title">
                Survey
            </span>
            <label class="surveyText">Platform:</label>
            <div class="input100">
                <select class="searchOp" name="platform" required>
                    <option value="AMT">AMT</option>
                    <option value="UpWork">UpWork</option>
                    <option value="Fiverr">Fiverr</option>
                    <option value="ClickWork">ClickWork</option>
                </select>
            </div>
        </div>
        <div class="wrap-input100 validate-input">
            <label class="surveyText" >Time spent looking for work:</label>
            <input class="input100" name="timelooking" type="number" max="100" min="0" required>
        </div>
        <div class="wrap-input100 validate-input">
            <label class="surveyText">Time spent working on task:</label>
            <input class="input100" name="timeworking" type="number" max="100" min="0" required>
        </div>

        <div class="wrap-input100 validate-input">
            <label class="surveyText">Wage(£/hr):</label>
            <input class="input100" name="wage" type="number" max="100" min="0" step="0.01" required>
        </div>

        <input class="login101-form-btn" type="submit" value="submit" name="submit">
    </form>

    <?php if (isset($view->insert)) : ?>
        <p><?php echo $view->insert; ?></p>
    <?php endif; ?>
    </div>
</div>
</body>