<head>
    <link rel="stylesheet" href="css/my-style.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>

<nav class="navbar navbar-inverse myNav">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">International Labour Organisation</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="#" class="nav-text">Logout</a></li>
        </ul>
    </div>
</nav>
<footer>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</footer>